### ISSUE TITLE
Error Analyzing Data

### ISSUE THREAD

**Issue by j75** [timlib/webXray#11]
```
==============
	Analyzing Data
==============
...
	================
	 General Summary
	================
		Total Pages OK:			7
		Total Pages FAIL:		0
		Total Pages Attempted:		7
		% Pages OK:			100.00%
		---
		Total Errors:			0
		---
		Total 3P Cookies:		0
		---
		Total Elements Requested:	96
		Total Elements Received:	95
		Total % Elements Received:	98.96%
		---
		3P Elements Requested:		0
		----------------------------------------
		Output written to ./reports/...
	=============================
	 Processing High-Level Stats 
	=============================
Traceback (most recent call last):
  File "run_webxray.py", line 365, in <module>
    interaction()
  File "run_webxray.py", line 253, in interaction
    interaction()
  File "run_webxray.py", line 269, in interaction
    analyze(db_name)
  File "run_webxray.py", line 305, in analyze
    analyzer.generate_stats_report()
  File "/home/.../webxray/webxray/Analyzer.py", line 547, in generate_stats_report
    csv_rows.append(('% 3P Elements Received SSL', round((total_elements_received_3p_ssl/total_elements_received_3p)*100,self.num_decimals)))
ZeroDivisionError: division by zero
```

**Comment by neilzone** [comment]
At a guess, it's because the page you are querying has no third party elements, meaning that the calculation on line 547 results in total_elements_received_3p being 0, and trying to divide by 0 fails.

Replacing line 547 of Analyzer.py with the following has worked for me:

                         if total_elements_received_3p>0:
                                 csv_rows.append(('% 3P Elements Received SSL', round((total_elements_received_3p_ssl/total_elements_received_3p)*100,self.num_decimals)))
                         else:
                                 csv_rows.append(('% 3P Elements Received SSL', 0))

**Comment by j75** [comment]
Yes, that fixed my problem - thank you!
But then I stumbled on another error:
```
...
	=========================================
	 Processing Aggregated 3P SSL Use Report 
	=========================================
Traceback (most recent call last):
  File "./run_webxray.py", line 365, in <module>
    interaction()
  File "./run_webxray.py", line 269, in interaction
    analyze(db_name)
  File "./run_webxray.py", line 312, in analyze
    analyzer.generate_aggregated_3p_ssl_use_report()
  File "/home/.../webxray/Analyzer.py", line 754, in generate_aggregated_3p_ssl_use_report
    'Owner Country', 'Owner Lineage')
IndexError: list assignment index out of range
```
The line 754 may be different from the original one, because I used before `autopep8` to format the code.

**Comment by neilzone** [comment]
What is your line 754?

**Comment by j75** [comment]
Yes, it was that and it fixed the problem!
Thank you very much for your cooperation.
