### ISSUE TITLE
FileNotFoundError - Setup issues

### ISSUE THREAD

**Issue by futurety-user** [timlib/webXray#39]
Hello, we are attempting to use webXray, but the initial setup instructions/test file are not working for us. We followed the setup instructions found [here ](https://webxray.org/#install_webXray), but when testing the example_sites.txt file initially we keep getting the error below. We are working on Windows 11. Thanks for any advice

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "C:\Users\User\webXray\webxray\Collector.py", line 107, in process_tasks_from_queue
    browser_driver      = ChromeDriver(self.browser_config, port_offset=process_num)
  File "C:\Users\User\webXray\webxray\ChromeDriver.py", line 134, in __init__
    subprocess.Popen(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\webXray\run_webxray.py", line 658, in <module>
    interaction()
  File "C:\Users\User\webXray\run_webxray.py", line 222, in interaction
    collect(db_name, pages_file_name)
  File "C:\Users\User\webXray\run_webxray.py", line 331, in collect
    collector.run(task='process_tasks_from_queue', pool_size=pool_size)
  File "C:\Users\User\webXray\webxray\Collector.py", line 701, in run
    myPool.map(self.process_tasks_from_queue, process_num)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by timlib** [comment]
hey, I can't test on windows b/c I don't have a windows machine handy, but it seems to be it is having trouble launching chrome.

if you look at this line: https://github.com/timlib/webXray/blob/master/webxray/ChromeDriver.py#L78

you'll see where it is trying to launch chrome - it could be that isn't work, or you have a unique install of chrome.

I'd suggest poking around on that path, but I'll leave this open as a something for me to review.
